// angularapp/angular-app/src/users/users/users.component.ts
import { Component } from '@angular/core';
import {HttpClient} from "@angular/common/http";
import {UserService} from "../user.service";
import { NgForm } from '@angular/forms';

export interface UserObject {
    users: User[]
}

export interface User {
    id: number;
    username: string;
    email: string;
    createdAt: Date;
    updatedAt: Date;
    verified: boolean;
    age: number;
}

@Component({
  selector: 'app-users',
  templateUrl: './users.component.html',
  styleUrls: ['./users.component.scss']
})
export class UsersComponent {
    public users: User[] = [];
    newUser: User = { id: 0, username: '', email: '', createdAt: new Date(), updatedAt: new Date(), verified: false, age: 0 };

    constructor (
        private userService: UserService
    ) { }

    ngOnInit(): void {
        this.userService.getUsers().subscribe((users) => {
            this.users = users.users;
        });
    }

    addUser(userForm: NgForm) {
        if (userForm.valid) {
            const startProcessingTime = performance.now();

            this.userService.addUser(this.newUser).subscribe((response) => {
                console.log('User added successfully:', response);
                this.newUser = { id: 0, username: '', email: '', createdAt: new Date(), updatedAt: new Date(), verified: false, age: 0 };
                userForm.resetForm();

                const endProcessingTime = performance.now(); // Mark the end time
                const processingTime = endProcessingTime - startProcessingTime;
                console.log('addNewUser Processing Time:', processingTime, 'ms');
                this.ngOnInit();
            });
        }
    }
}

<div>
    <form #userForm="ngForm" (ngSubmit)="addUser(userForm)"  class="user-form-container">
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" id="username" name="username" [(ngModel)]="newUser.username" required>
            <div *ngIf="userForm.controls['username']?.invalid && (userForm.controls['username'].dirty || userForm.submitted)">
                <div class="error" *ngIf="userForm.controls['username'].hasError('required')">Username is required.</div>
            </div>
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input type="email" id="email" name="email" [(ngModel)]="newUser.email" required pattern="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}">
            <div *ngIf="userForm.controls['email']?.invalid && (userForm.controls['email'].dirty || userForm.submitted)">
                <div class="error" *ngIf="userForm.controls['email'].hasError('required')">Email is required.</div>
                <div class="error" *ngIf="userForm.controls['email'].hasError('email')">Invalid email format.</div>
            </div>
        </div>
        <div class="form-group">
            <label for="age">Age</label>
            <input type="number" id="age" name="age" [(ngModel)]="newUser.age" required>
        </div>
        <div class="form-group">
            <label for="verified">Verified</label>
            <input type="checkbox" id="verified" name="verified" [(ngModel)]="newUser.verified">
        </div>
        <button type="submit">Add User</button>
    </form>
</div>
<div class="list" *ngFor="let user of users">
    <div class="list__item">
        <div class="left-content">
            <div class="id">{{ user.id }}</div>
            <div class="name">{{ user.username }}</div>
            <div class="mail">{{ user.email }}</div>
        </div>
        <div class="right-content">
            <div class="date">{{ user.createdAt | date: 'yyyy-MM-dd HH:mm:ss' }}</div>
            <div class="date">{{ user.updatedAt | date: 'yyyy-MM-dd HH:mm:ss' }}</div>
            <div class="age">{{ user.age }}</div>
            <input type="checkbox" [checked]="user.verified">
        </div>
    </div>
</div>

// reactapp/my-app/src/users/users.tsx
import React, {useState, useEffect, FormEvent} from 'react';
import "./users.scss";
import {addUser, getUsers} from "./user.service";

export interface UserObject {
    users: User[]
}

export interface User {
    id: number;
    username: string;
    email: string;
    createdAt: Date;
    updatedAt: Date;
    verified: boolean;
    age: number;
}

const Users = () => {
    const [users, setUsers] = useState<User[]>([]);

    useEffect(() => {
        getRecentUsers()
    }, []);

    const [newUser, setNewUser] = useState<User>({
        id: 0,
        username: '',
        email: '',
        createdAt: new Date(),
        updatedAt: new Date(),
        verified: false,
        age: 0
    });

    const addNewUser = async (e: FormEvent<HTMLFormElement>) => {
        e.preventDefault();
        const startProcessingTime = performance.now();

        try {
            const response = await addUser(newUser);
            console.log('User added successfully:', response);

            setNewUser({
                id: users.length + 1,
                username: '',
                email: '',
                createdAt: new Date(),
                updatedAt: new Date(),
                verified: false,
                age: 0,
            });
            getRecentUsers();

            const endProcessingTime = performance.now(); // Mark the end time
            const processingTime = endProcessingTime - startProcessingTime;
            console.log('addNewUser Processing Time:', processingTime, 'ms');
        } catch (error) {
            console.error(error);
        }
    };

    const formatDate = (date: Date) => {
        const pad = (n: number) => (n < 10 ? `0${n}` : n);

        const year = date.getFullYear();
        const month = pad(date.getMonth() + 1); // Months are zero-based
        const day = pad(date.getDate());
        const hours = pad(date.getHours());
        const minutes = pad(date.getMinutes());
        const seconds = pad(date.getSeconds());

        return `${year}-${month}-${day} ${hours}:${minutes}:${seconds}`;
    };

    const getRecentUsers = (): void => {
        getUsers()
            .then((data) => {
                setUsers(data.users);
            })
            .catch((error) => {
                console.error(error);
            });
    }

    return (
        <div>
            <form onSubmit={addNewUser} className="user-form-container">
                <div className="form-group">
                    <label htmlFor="username">Username</label>
                    <input
                        type="text"
                        id="username"
                        name="username"
                        value={newUser.username}
                        onChange={(e) => setNewUser({ ...newUser, username: e.target.value })}
                        required
                    />
                </div>
                <div className="form-group">
                    <label htmlFor="email">Email</label>
                    <input
                        type="email"
                        id="email"
                        name="email"
                        value={newUser.email}
                        onChange={(e) => setNewUser({ ...newUser, email: e.target.value })}
                        required
                    />
                </div>
                <div className="form-group">
                    <label htmlFor="age">Age</label>
                    <input
                        type="number"
                        id="age"
                        name="age"
                        value={newUser.age}
                        onChange={(e) => setNewUser({ ...newUser, age: Number(e.target.value) })}
                        required
                    />
                </div>
                <div className="form-group">
                    <label htmlFor="verified">Verified</label>
                    <input
                        type="checkbox"
                        id="verified"
                        name="verified"
                        checked={newUser.verified}
                        onChange={(e) => setNewUser({ ...newUser, verified: e.target.checked })}
                    />
                </div>
                <button type="submit">Add User</button>
            </form>
            <div className="list">
                {users.map((user) => (
                    <div className="list__item" key={user.id}>
                        <div className="left-content">
                            <div className="id">{user.id}</div>
                            <div className="name">{user.username}</div>
                            <div className="mail">{user.email}</div>
                        </div>
                        <div className="right-content">
                            <div className="date">{formatDate(new Date(user.createdAt))}</div>
                            <div className="date">{formatDate(new Date(user.updatedAt))}</div>
                            <div className="age">{user.age}</div>
                            <input type="checkbox" checked={user.verified} readOnly />
                        </div>
                    </div>
                ))}
            </div>
        </div>
    );
};

export default Users;
